gem 'jekyll'
gem 'livereload'
gem 'guard'
gem 'guard-jekyll-plus'
gem 'guard-livereload'
gem 'ffi'
gem 'mercenary'
gem 'redcarpet'
gem 'jekyll-watch'
gem 'classifier-reborn'
gem 'guard-bundler'
gem 'win32console'
gem 'wdm'

source 'http://rubygems.org'